/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Fast;

import Homepage.UserHomepage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author AA
 */
public class FastCash extends JFrame implements ActionListener {
    /**
     * 
     * Creates new form FastClass
     */
  

    public FastCash() {
        initComponents();
          addActionListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FAST CASH");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 650, -1));

        jButton1.setText("1000");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 179, 41));

        jButton2.setText("2000");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 175, 41));

        jButton3.setText("2500");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 179, 41));

        jButton4.setText("3000");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 175, 41));

        jButton5.setText("5000");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 179, 40));

        jButton6.setText("10000");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 175, 41));

        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 201, 44));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast/adsfg.gif"))); // NOI18N
        jLabel2.setText("x");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
this.dispose();
Homepage.UserHomepage obj =new UserHomepage();
obj.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastCash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        try {
            JButton button = (JButton) e.getSource();
            String buttonText = button.getText();
            switch (buttonText) {
                case "1000":
                    withdrawAmount(1000);
                    break;
                case "2000":
                    withdrawAmount(2000);
                    break;
                case "2500":
                    withdrawAmount(2500);
                    break;
                case "3000":
                    withdrawAmount(3000);
                    break;
                case "5000":
                    withdrawAmount(5000);
                    break;
                case "10000":
                    withdrawAmount(10000);
                    break;
                case "Back":
                    goBack();
                    break;
                default:
                    break;
            }
        } catch (IOException ex) {
            ex.printStackTrace();
            // Handle the exception
        }
    }

    private void addActionListeners() {
        jButton1.addActionListener(this);
        jButton2.addActionListener(this);
        jButton3.addActionListener(this);
        jButton4.addActionListener(this);
        jButton5.addActionListener(this);
        jButton6.addActionListener(this);
        jButton7.addActionListener(this);
    }

    private String getAccNo() {
        String cardno = JOptionPane.showInputDialog(null, "Account No: ");
        return cardno;
    }

    private void withdrawAmount(int i) throws IOException {
        String amount = null, line = null, delimiter = ",";
        String accnumber = getAccNo();
        String accNo = null, customerName = null, accType = null, accBal = null, accPin = null;
        String filePath = "D:" + File.separator + "DHA SUFFA" + File.separator + "Semester 2" + File.separator
                + "OOP LAB" + File.separator + "Prject" + File.separator + "ATM Management System (2)gfdga"
                + File.separator + "ATM Management System" + File.separator + "ATMSystem" + File.separator + "data"
                + File.separator + "accounts" + File.separator + accnumber + ".txt";

        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            while ((line = br.readLine()) != null) {
                String[] data = line.split(delimiter);
                accNo = data[0];
                customerName = data[1];
                accType = data[2];
                accBal = data[3];
                accPin = data[4];
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "The given account number doesn't exist, please recheck.",
                    "Error Message", JOptionPane.ERROR_MESSAGE);
        }

        if (Integer.parseInt(accBal) > i) {
            int temp = Integer.parseInt(accBal) - i;
            System.out.print(temp);
            JOptionPane.showMessageDialog(null, "Withdrawn amount: " + i);
            savePerson(accNo, customerName, accType, temp, accPin);
        } else {
            JOptionPane.showMessageDialog(null, "Insufficient Balance!");
        }
    }

    private void savePerson(String cardno, String name, String acctype, int bal, String pin) throws IOException {
        String filePath = "D:" + File.separator + "DHA SUFFA" + File.separator + "Semester 2" + File.separator
                + "OOP LAB" + File.separator + "Prject" + File.separator + "ATM Management System (2)gfdga"
                + File.separator + "ATM Management System" + File.separator + "ATMSystem" + File.separator + "data"
                + File.separator + "accounts" + File.separator + cardno + ".txt";
        FileWriter fw = new FileWriter(filePath);
        fw.write(cardno + "," + name + "," + acctype + "," + bal + "," + pin);
        fw.close();
    }

    private void goBack() {
        JOptionPane.showMessageDialog(this, "Going back");
        
    }

  
}
